FROM python:3.12.7-slim-bookworm@sha256:60d9996b6a8a3689d36db740b49f4327be3be09a21122bd02fb8895abb38b50d

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/python
WORKDIR /app
COPY requirements-worker.txt ./requirements-worker.txt
RUN pip install --no-cache-dir --require-hashes -r requirements-worker.txt
COPY python ./python
USER 65532:65532
EXPOSE 8081
ENTRYPOINT ["python", "-m", "workers"]
